require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  NewCops: enable
  UseCache: true
  TargetRubyVersion: 3.0.2
  Exclude:
    - 'db/schema.rb'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'tmp/**/*'
    - 'spec/*_helper.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
    - 'spec/factories/**/*.rb'

Style/Documentation:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/MultipleExpectations:
  Max: 5

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/NamedSubject:
  Enabled: false

RSpec/LetSetup:
  Enabled: false
